---
- hosts: localhost

  gather_facts: True

  # Variables precedence (since Ansible version 2.x):
  #     - role defaults [Tasks defined outside of a role will see the last role’s defaults.]
  #     - inventory file or script group vars [Variables defined in inventory file or provided by dynamic inventory.]
  #     - inventory group_vars/all
  #     - playbook group_vars/all
  #     - inventory group_vars/*
  #     - playbook group_vars/*
  #     - inventory file or script host vars [Variables defined in inventory file or provided by dynamic inventory.]
  #     - inventory host_vars/*
  # (*) - playbook host_vars/*
  #     - host facts / cached set_facts [When created with set_facts’s cacheable option, variables will have the high
  #                                      precedence in the play, but will be the same as a host facts precedence when
  #                                      they come from the cache.]
  #     - inventory host_vars/*
  #     - playbook host_vars/*
  #     - host facts
  #     - play vars
  #     - play vars_prompt
  #     - play vars_files
  #     - role vars (defined in role/vars/main.yml)
  #     - block vars (only for tasks in block)
  #     - task vars (only for the task)
  #     - include_vars
  #     - set_facts / registered vars
  #     - role (and include_role) params
  #     - include params
  #     - extra vars (always win precedence)
  vars:
    node_type: ""
    node_name: ""
    node_private_ip: ""
    master_node_names: ""
    master_node_ips: ""
    ca_crt_b64: ""
    ca_key_b64: ""
    api_server_crt_b64: ""
    api_server_key_b64: ""
    service_account_crt_b64: ""
    service_account_key_b64: ""
    etcd_version: ""

  pre_tasks:
    - name: "{{ ansible_play_name }} - check required inputs"
      fail:
        msg: "[ERROR] - '{{ item }}' variable is not set"
      when:
        - vars[item]|length == 0
      loop:
        - node_type
        - node_name
        - node_private_ip
        - master_node_names
        - master_node_ips
        - ca_crt_b64
        - ca_key_b64
        - api_server_crt_b64
        - api_server_key_b64
        - service_account_crt_b64
        - service_account_key_b64
        - etcd_version

  tasks:
    - block:
        - include_role:
            name: ansible-role-etcd
          vars:
            etcd_version: "{{ etcd_version }}"
            etcd_node_name: "{{ node_name }}"
            etcd_node_private_ip: "{{ node_private_ip }}"
            etcd_initial_cluster_member_names: "{{ master_node_names }}"
            etcd_initial_cluster_member_ips: "{{ master_node_ips }}"
            etcd_ca_cert: "{{ ca_crt_b64|b64decode }}"
            etcd_tls_cert: "{{ api_server_crt_b64|b64decode }}"
            etcd_tls_key: "{{ api_server_key_b64|b64decode }}"

        - include_role:
            name: ansible-role-k8s-control-plane
          vars:
            control_plane_node_name: "{{ node_name }}"
      # block type
      when:
        - node_type|lower == 'master'
